// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYpGsCtGa8eQTVUJsVTAupNOk3E_qoHQ',
    appId: '1:133699507338:android:fa2cb5639eaca91b250973',
    messagingSenderId: '133699507338',
    projectId: 'my-book-journal-37c6e',
    storageBucket: 'my-book-journal-37c6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4zmDQSTjJlLbAM3LWuGBNft6HYC3WyA',
    appId: '1:133699507338:ios:c06a456338679063250973',
    messagingSenderId: '133699507338',
    projectId: 'my-book-journal-37c6e',
    storageBucket: 'my-book-journal-37c6e.firebasestorage.app',
    androidClientId: '133699507338-luki7lponsbj5b9cn3rvku0nit5itnng.apps.googleusercontent.com',
    iosClientId: '133699507338-rplo42j5slg26hl5gbtd4gksoi0j4vto.apps.googleusercontent.com',
    iosBundleId: 'com.example.voiceJournaling',
  );
}
